### PR TITLE
Fixed typos, small improvements

### PR DESCRIPTION
**Pull request by urbalazs**

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @urbalazs, do you really want to translate this big document?

**Comment by mgruner** [comment]
Hello @urbalazs, thanks a lot for your fixes, as usual! I merged this in 286e269, but without the po4a.conf. At this point I am not convinced that making the dev manual translatable is actually worth the effort / that there is enough interest in translating this document. If you still feel it would be good and really want to translate it, please let me know. We can definitely add it. Again, thank you so much!
Best regards, Martin

**Comment by urbalazs** [comment]
Hello @mgruner, one of our customers needs this document in Hungarian, so I have to translate it for him. I sent the po4a.conf, because I have to create it for the translation. If you think, it is not useful for the project, then it is OK not to add it to the repository. But the Hungarian translation process will continue…

**Comment by mgruner** [comment]
Hello @urbalazs, thanks for the update. I added the needed files in 61659c7 and also created a transifex resource at https://www.transifex.com/otrs/OTRS/doc-developer/. It would be great if you could upload your current state (there is a .po file upload possibility) and keep translating there so that others could profit from it and possibly collaborate. Ok?

**Comment by urbalazs** [comment]
I uploaded my current state of translation to Transifex. 30% is done, translation is in progress…

**Comment by mgruner** [comment]
Wow, nice! I will publish it once it is more complete.
And what about the admin manual, do you plan to translate that as well?

Regards, Martin

Am 04.11.15 um 10:08 schrieb Úr Balázs:
> I uploaded my current state of translation to Transifex. 30% is done,
> translation is in progress…
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/doc-developer/pull/5#issuecomment-153647119>.
> 

-- 
Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Mobile Kommunikation und transparente Prozesse - Mit der OTRS Business
Solution™ Managed 5 schnell und ohne eigene IT-Ressourcen starten  -
Jetzt neue Features entdecken und bestellen
https://www.otrs.com/neu-in-otrs-business-solution-5-mobile-kommunikation-transparente-prozesse/?lang=de

**Comment by urbalazs** [comment]
Yes, all the manuals will be translated. Admin manual is in progress too, but before that I have to finish the ITSM and the developer manual, because our customers need them.
I translated the OTRS-appliance manual, but I don't find it on Transifex to upload my translation. Can you add it to Transifex? Or shall I make a pull request? I have localized screenshots, too.

**Comment by mgruner** [comment]
Thanks for the update! The OTRS appliance has been discontinued a while ago.

Am 04.11.15 um 11:44 schrieb Úr Balázs:
> Yes, all the manuals will be translated. Admin manual is in progress
> too, but before that I have to finish the ITSM and the developer manual,
> because our customers need them.
> I translated the OTRS-appliance manual, but I don't find it on Transifex
> to upload my translation. Can you add it to Transifex? Or shall I make a
> pull request? I have localized screenshots, too.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/doc-developer/pull/5#issuecomment-153680975>.
> 

-- 
Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Mobile Kommunikation und transparente Prozesse - Mit der OTRS Business
Solution™ Managed 5 schnell und ohne eigene IT-Ressourcen starten  -
Jetzt neue Features entdecken und bestellen
https://www.otrs.com/neu-in-otrs-business-solution-5-mobile-kommunikation-transparente-prozesse/?lang=de

**Pull request closed without merging**
